version: '3.4'
networks:
  isolation-network:
    driver: bridge

services:
  greencharge.local:
    image: prosody/prosody
    hostname: greencharge.local
    ports:
      - "5222:5222"
      - "5280:5280"
    volumes:
        - ./etc/prosody:/etc/prosody
    environment:
        - LOCAL=demo
        - DOMAIN=greencharge.local
        - PASSWORD=demo
    networks:
      - isolation-network

  greencharge.simulator:
      hostname: 
         greencharge.simulator
      image: gcsim:latest
      ports:
        - "10021:10021"
        - "5678:5678"
      networks:
        - isolation-network
      environment:
        - PYTHONPATH=/home/gc/simulator
        - PATH=/home/gc/simulator/bin:$PATH
      volumes:
        - ./users/demo:/home/gc
        - ./Dockers/gcsim/gcsimulator:/home/gc/simulator
      stdin_open: true
      tty: true
      # command: ["sh", "-c", "pip3 install debugpy -t /tmp && python3 /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 /usr/local/lib/python3.8/dist-packages/gcsimulator/starter.py "]
  gcscheduler:
     image: gcscheduler:latest
     ports:
       - "10023:10023"
     networks:
       - isolation-network
     volumes:
       - ./Dockers/gcscheduler/scheduler:/home/scheduler
     stdin_open: true
     tty: true
    
